module.exports = {
  "ALIVE_IMG": "https://raw.githubusercontent.com/Niko-AND-Janiya/ANJU-DATA/refs/heads/main/WhatsApp%20Image%202024-09-08%20at%209.00.17%20PM.jpeg",
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "public",
  "BOT_NUMBER": "94720267441",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": false,
  "AUTO_VOICE": false,
  "AUTO_STICKER": false,
  "AUTO_REPLY": false,
  "AUTO_REACT": false,
  "WELCOME": false,
  "ANTI_BAD": false,
  "ANTI_BOT": false,
  "ANTI_LINK": false,
  "ALLWAYS_ONLINE": false,
  "MOROCCO_BLOCK": false,
  "BTN_MSG": false,
  "OWNER_NAME": "MR Rowdy",
  "NEWS_JID": "",
  "AUTO_TYPING": false,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false,
  "OWNER_REACT": false,
  "EMOJI": "🏷"
};
